login.query=SELECT * FROM users WHERE username = '%s' AND password = '%s'
search.query=SELECT name, price FROM products WHERE name LIKE '%%%s%%'
delete.query=DELETE FROM users WHERE id = 
ping.cmd=ping -c 4 
cat.cmd=cat 
nslookup.cmd=nslookup 
xss.search.open=<h2>Results for: 
xss.search.close=</h2>
xss.error.open=<html><body><div class='error'>
xss.error.close=</div></body></html>
xss.comment.insert=INSERT INTO comments (username, comment) VALUES ('%s', '%s')
xss.comment.open=<p><strong>
xss.comment.mid=:</strong> 
xss.comment.close=</p>